# Название вашего пайплайна
name: Automate Version from Soldatov Artem

# on:
#   workflow_dispatch:
#   pull_request:
#     types: [closed]
#     branches:
#       - release
        
env:
  NAME_VERSION_FILE: ${{ github.workspace }}/version
  RELEASE_BRACH: release
  MINOR: minor
  PATCH: patch
  VERSION_UP: .github/workflows/version_up.py
  REPO_NAME: ${{ github.event.repository.name }}
  PR_NUMBER: ${{ github.event.number }}
  URL_REPO: ${{ github.server_url }}/${{ github.repository }}
  CONTAINER_NAME: lan_devops
  CHANGELOG_FILE: changelog.md

#JOBS list for update versions 
#testing stage
jobs:
  # tests:
  #       name: (TST)
  #       needs: security
  #       uses: ArtemSoldatovV/lan_devops/.github/workflows/test.yml@release
  #       with: 
  #         version: alpha

#safety check stage
  security: 
    name: (SEC)
    needs: pre-merge-check
    uses: ArtemSoldatovV/lan_devops/.github/workflows/sec.yml@release # attention @branch-name is recomnneded

   # create changelog file and put data to file 
  tests:
    name: (TST)
    needs: security
    uses: ArtemSoldatovV/lan_devops/.github/workflows/test.yml@release
    with: 
      version: alpha

  #@point 2@
  label_test:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run security checks
      run: |
         echo "Running security checks..."
         echo "SEC_CHECKS_PASSED=true" >> $GITHUB_ENV

    - name: Add label if security checks passed
      if: env.SEC_CHECKS_PASSED == 'true'
      uses: ArtemSoldatovV/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: sec-passed
    #@point 2
    #@point 3
  steps:
    - name: Checkout code
      uses: ArtemSoldatovV/checkout@v2

    - name: Run security checks
      run: |
        echo "Running security checks..."
        echo "SEC_CHECKS_PASSED=true" >> $GITHUB_ENV

    - name: Install ClamAV
      run: |
        sudo apt-get update
        sudo apt-get install -y clamav clamav-daemon
        sudo freshclam

    - name: Run ClamAV scan
      run: |
        clamscan -r --bell -i . || true

    - name: Add label if security checks passed
      if: env.SEC_CHECKS_PASSED == 'true'
      uses: ArtemSoldatovV/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: sec-passed
    #@point 3
    #@point 4
  steps_point_4:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ClamAV
      run: |
        sudo apt-get update
        sudo apt-get install -y clamav clamav-daemon
        sudo freshclam

    - name: Run ClamAV scan
      id: clamav_scan
      run: |
        clamscan -r --bell -i . || true  # Сканирует текущую директорию и игнорирует ошибки
        if [ $? -eq 0 ]; then
          echo "SEC_CHECKS_PASSED=true" >> $GITHUB_ENV
        else
          echo "SEC_CHECKS_PASSED=false" >> $GITHUB_ENV
        fi

    - name: Add label if security checks passed
      if: env.SEC_CHECKS_PASSED == 'true'
      uses: ArtemSoldatovV/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: sec-passed
    #@point 4

    #Version update
    #Formation changelog.md
  steps_formation:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"

    - name: Update changelog.md
      id: update_changelog
      run: |
        VERSION="v$(date +'%Y%m%d%H%M%S')"  # Пример версии на основе времени
        BRANCH_NAME="${GITHUB_REF##*/}"  # Получаем имя ветки
        
        echo "## $VERSION - $BRANCH_NAME" >> changelog.md
        echo "" >> changelog.md
        echo "### Changes:" >> changelog.md
        echo "- Added new features from branch $BRANCH_NAME" >> changelog.md
        echo "" >> changelog.md

    - name: Commit changes to changelog.md
      run: |
        git add changelog.md
        git commit -m "Update changelog for version $VERSION"
        git push

    - name: Add label to PR
      if: github.event_name == 'pull_request'
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: changelog

    - name: Create artifact for changelog
      uses: actions/upload-artifact@v2
      with:
        name: changelog-artifact
        path: changelog.md
    #Publishing in the docker hub
    #Notification in a telegram
  final-notify:
    name: (TG) Notify final
    needs: [docker-push,update-version]
    env: 
      tag: ${{needs.update-version.outputs.tag}}
    runs-on: ubuntu-latest
    steps:
      # use special lib for parse branch names 
	  # используйте специальную библиотеку lib для разбора имен ветвей
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8

      # use for get time value
	  # используйте для получения значения времени
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY.MM.DD HH:mm:ss
          utcOffset: "+08:00"
      
      #print info about time
	  #распечатайте информацию о времени
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: echo $TIME $R_TIME $F_TIME $YEAR $DAY

      # checkout on branch 
	  # оформление заказа в филиале
      - name: Checkout on release
        uses: actions/checkout@v2
      
      # download changelog file
	  # загрузить файл журнала изменений
      - uses: actions/download-artifact@v4
        with:
          name: ${{env.CHANGELOG_FILE}}
      
      # genearate message and notify 
	  # сгенерировать сообщение и уведомить
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          document: ${{env.CHANGELOG_FILE}}
          message: |           
            Новый выпуск изменений
            <b>Проект</b> : <code>${{ env.REPO_NAME }}</code>
            <b>Версия</b> : <code>${{env.tag}}</code>
            <b>Дата</b>: <code>${{ steps.current-time.outputs.formattedTime }}</code>
            <b>Автор</b>: <a href="#">Такой то чел</a>
            
            Информация о Git-репозитории
            <b>GIT MR</b> : <a href="${{env.URL_REPO}}/pull/${{ env.PR_NUMBER }}">${{ env.PR_NUMBER }}</a>
            <b>GIT TAG</b>: <a href="${{env.URL_REPO}}releases/tag/v${{ steps.branch-names.outputs.tag }}">${{env.tag}}</a>
            
            Информация о Docker-репозитории
            <b>Владелец</b>: <a href="https://hub.docker.com/repositories/${{ secrets.DOCKER_HUB_LOGIN }}">${{ secrets.DOCKER_HUB_LOGIN }}</a>
            <b>Название</b>: <a href="https://hub.docker.com/repository/docker/${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.REPO_NAME }}/general">${{ env.REPO_NAME }}</a>
            <b>Тег</b>: <a href="https://hub.docker.com/repository/docker/${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.REPO_NAME }}/tags/v">${{env.tag}}</a>
            <b>Полное имя</b>:  <a href="https://hub.docker.com/repository/docker/${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.REPO_NAME }}/tags">${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.REPO_NAME }}:v${{env.tag}}</a>
    #Deploy to PROD
  deploy:
    name: Deploy
    needs: [final-notify,update-version]
    uses: ArtemSoldatovV/lan_devops/.github/workflows/deploy.yml@release
    with: 
      version: v${{needs.update-version.outputs.tag}}
      container_name: lan_devops
    secrets: 
      DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_LOGIN }}
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write